# Native Dawn dependency for DirectWebGPU. Keep this revision aligned with
# cmake/FetchEmdawnwebgpu.cmake and tools/build-tint.sh.

include(FetchContent)

set(MOBILEGL_DAWN_REF "b465e23d19a5e27402d80191c0f8de1fb3b385b5"
    CACHE STRING "Pinned Dawn revision for native DirectWebGPU")
set(MOBILEGL_DAWN_SOURCE_DIR "" CACHE PATH
    "Optional pre-populated Dawn checkout (avoids network fetch)")

set(DAWN_FETCH_DEPENDENCIES ON CACHE BOOL "" FORCE)
set(DAWN_BUILD_MONOLITHIC_LIBRARY ON CACHE BOOL "" FORCE)
set(DAWN_BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(DAWN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(DAWN_BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(DAWN_BUILD_NODE_BINDINGS OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_D3D11 OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_D3D12 OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_METAL OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_DESKTOP_GL OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_OPENGLES OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_NULL OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_SWIFTSHADER OFF CACHE BOOL "" FORCE)
set(DAWN_ENABLE_VULKAN ON CACHE BOOL "" FORCE)
set(DAWN_USE_X11 ON CACHE BOOL "" FORCE)
set(DAWN_USE_WAYLAND OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_CMD_TOOLS OFF CACHE BOOL "" FORCE)
set(TINT_BUILD_SPV_READER ON CACHE BOOL "" FORCE)
set(TINT_BUILD_WGSL_WRITER ON CACHE BOOL "" FORCE)

if(MOBILEGL_DAWN_SOURCE_DIR)
    set(FETCHCONTENT_SOURCE_DIR_DAWN "${MOBILEGL_DAWN_SOURCE_DIR}")
endif()

FetchContent_Declare(
    dawn
    GIT_REPOSITORY https://dawn.googlesource.com/dawn
    GIT_TAG "${MOBILEGL_DAWN_REF}"
    GIT_SHALLOW TRUE
)
FetchContent_MakeAvailable(dawn)

if(NOT TARGET dawn::webgpu_dawn)
    message(FATAL_ERROR "Pinned Dawn did not export dawn::webgpu_dawn")
endif()
